project:
  type: website

website:
  title: "Tereza Lacerda"
  navbar:
    background: primary
    search: true
    right:
      - text: "Sobre Mim"
        file: about.qmd
      - icon: github
        href: https://github.com/terezalacerda
      - icon: twitter
        href: https://twitter.com/tereza_lacerda
      - icon: spotify
        href: https://open.spotify.com/user/therezzza
      - icon: linkedin
        href: https://www.linkedin.com/in/terezalacerda/
      - icon: instagram
        href: https://www.instagram.com/_cherry.py/
  page-footer:
    left: "Blog feito com [Quarto](https://quarto.org/)"
    right:
      - icon: github
        href: https://github.com/terezalacerda
      - icon: twitter
        href: https://twitter.com/tereza_lacerda
format:
  html:
    theme: minty
    css: styles.css

editor: visual

