project:
  type: website

website:
  title: "Tereza Lacerda"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/terezalacerda
      - icon: twitter
        href: https://twitter.com/tereza_lacerda
  page-footer:
    left: "Blog feito com [Quarto](https://quarto.org/)"
    right:
      - icon: github
        href: https://github.com/terezalacerda
      - icon: twitter
        href: https://twitter.com/tereza_lacerda
format:
  html:
    theme: minty
    css: styles.css

editor: visual

