project:
  type: website

website:
  title: "terezalacerda"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/terezalacerda
      - icon: twitter
        href: https://twitter.com/tereza_lacerda
format:
  html:
    theme: sketchy
    css: styles.css

editor: visual

